### ISSUE TITLE
cant load kbdx

### ISSUE THREAD

**Issue by zeltak** [Angoll/KPass#1]
Hi and thx for the workflow.

KPass Setup won't let me choose my file during the setup  and its grayed out

<img width="651" alt="image" src="https://user-images.githubusercontent.com/498410/80897315-37c00b00-8cc5-11ea-8230-c845b92736b5.png">

any clue

**Comment by Angoll** [comment]
Hi @zeltak, thanks for the feedback.

I uploaded a modified version of the workflow in releases **KPass.without_extensionfilter.alfredworkflow** same workflow but without the file extension filter, so you will be able to select any file.

Please can you provide me with the version of KeepassXC that you are using?
And let me know if it fix the issue?

Thanks

**Comment by zeltak** [comment]
thx @Angoll 

i updated as instructed and it does work now! But i get an error

<img width="423" alt="image" src="https://user-images.githubusercontent.com/498410/80921816-a7c2a580-8d46-11ea-83db-35374adff858.png">

any clue?

best

Z

**Comment by Angoll** [comment]
Could you provide me the following info:
 - Mac OS version. 
 - The output of KeePassXC Debug Info. (you should be able to find it inside KeepassXC -> About KeepassXC Menu)

thanks

**Comment by zeltak** [comment]
macOS 10.15.4 (19E287)
MacBook Pro
Keepass 2.5.4

happy to help debug this

best

Z

**Comment by Angoll** [comment]
@zeltak

Could you tell me at what step did it fail?

1. kdbx file selector
2. Keychain selector
3. Ask for the kdbx password
4. completes the configuration

I have the same system configuration and I couldn't reproduce the error.


You can try to configure the KPass integration manually:

1. Create a keychain password with the following command:

`security add-generic-password -a $(id -un) -c 'kaiw' -C 'kaiw' -D 'KeepasXC Integration' -j 'Alfred KeepasXC Integration Database' -s 'KPass_AlfredWorkflow' -w $PASSWORD -U $KEYCHAIN`

Where:
 - $PASSWORD should be your password in quotes. ex:  "mypass"
 - $KEYCHAIN is the full path of your keychain file.  ex: "/Users/$(id -un)/Library/Keychain/loging.keychain-db"

2. Open Alfred Preferences -> workflow -> [x] and set the following environment variables:
 - Name:  **database**
    Value:  full path tho the kdbx file
 - Name:  **keychain**
    Value:  full path to the keychain


Let me know if that helps,
best
