### ISSUE TITLE
After setup, passwords don't load. 

### ISSUE THREAD

**Issue by jt196** [Angoll/KPass#10]
Hi there - have set up the Workflow (including making a symlink to the KeePassXC cli). Keychain item and DB are correctly configured. 

When I type `kpass` and an item, Alfred just defaults to an Amazon/Google etc web search. If I type `kpassloader`, the system says `Please loading database` for a second or so, then it goes back to the Amazon/Google screen. Seems like something's loading but no error messages come up, and nothing happens. 

I've tried playing around with the permissions on KPXC file, I've used the cli successfully a couple of times. Not sure what else to do at this point.

Using Alfred v4.2.1 (1187) btw. 

```
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.6
```

**Comment by jt196** [comment]
This is the line on debugger:

`/Users/<userdir>/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/0DAF1653-F20D-4535-A89A-4E4C3814FDD0: line 25: jq: command not found`

**Comment by jt196** [comment]
```
[16:45:07.149] KPass[Keyword] Processing complete
[16:45:07.150] KPass[Keyword] Passing output '' to Run Script
[16:45:27.298] KPass[Script Filter] Queuing argument '(null)'
[16:45:30.037] KPass[Script Filter] Script with argv '(null)' finished
[16:45:30.041] STDERR: KPass[Script Filter] libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
/Users/<userdir>/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/F500562D-E508-4E72-90D7-11C782109241: line 47: jq: command not found
/Users/<userdir>/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/F500562D-E508-4E72-90D7-11C782109241: line 25: jq: command not found
/Users/<userdir>/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/F500562D-E508-4E72-90D7-11C782109241: line 25: jq: command not found
```
This is the rest of the debug log. Right at the beginning. The rest is those line 25 errors.

**Comment by Angoll** [comment]
Hello @jt196 
It seems that the issue is that you don't have installed the **jq** command line, you can install it using brew or ports.
You can find more info here: 
[https://stedolan.github.io/jq/download/](https://stedolan.github.io/jq/download/)

**jq** is a cli command that allows the processing of Json files/structures

**Comment by jt196** [comment]
Dagnammit I missed that - I can see it's on the dependencies list now I checked. Thanks for getting back to me.

**Comment by jt196** [comment]
```
[00:30:27.861] KPass[Script Filter] Queuing argument '(null)'
```
Quick test. No error messages, but no passwords pop up after jq installed. Restarted Alfred, KeepassXC, I'll do the machine in the morning unless there's something you can think of.

**Comment by jt196** [comment]
That's the log btw. It just hangs there saying 'Please loading database'.

**Comment by jt196** [comment]
OK Seems to be working now. 

Quick question @Angoll about the search behaviour. If I type `kpass ebay`, nothing turns up, however if I type `kpass shopping` (eBay is in the shopping folder) I can find it. Problem is, I have to remember which folder items are in with this behaviour. Is this correct behaviour or am I missing something?

**Comment by Angoll** [comment]
Hello, good to know that now its working

You can going to the Alfred Preferences, in the workflow open the kpass (script filter) and play on the Alfred filters results to find one that fits you better.

In theory I only lis all entries and I let the Alfred system to process and learn with the results.
