### ISSUE TITLE
Error while reading the database.

### ISSUE THREAD

**Issue by pdomineaux** [Angoll/KPass#11]
Hello,

I was too slow to reply before you close the previous issue but I still have the same issue.
Here is the complete error message copied from the clipboard :

```
Enter password to unlock /Users/myUser/Documents/Work/CFN/coffre-systeme.kdbx: Error while reading the database: Invalid credentials were provided, please try again. If this reoccurs, then your database file may be corrupt.
```

I know that my database is not corrupted as I can open it in KeepassXc.
I'm using KeepassXC 2.6.2
And the last version of your Workflow 2.1

I've also check the configuration of the workflow and each time I launched the kpassinit it untick the `keychainitem`.
If I tick it, it doesn't change anything.

<img width="687" alt="Keepass-cli-workflow" src="https://user-images.githubusercontent.com/9936170/99976480-c56b6100-2da3-11eb-8725-a9c0b1e5334a.png">

**Comment by pdomineaux** [comment]
I have to admit that the password contains this symbols : 
`'` and `!`
I think that's the issue. But I don't know how to fix that within your code.

**Comment by Angoll** [comment]
Hello thanks for your issue

The error message is generated by keepassxc-cli.
Can you open a terminal and check if the following commands works or not:

- This command will show you the password stored in your keychain, this is the password used by KPass to unlock the database.

```
security find-generic-password -a $(id -un) -c 'kpas' -C 'kpas' -s "KPass_AlfredWorkflow" -w "/Users/.........../Library/Keychains/login.keychain-db"
```

- If the above works, this is combined with the keepassxc-cli

```
security find-generic-password -a $(id -un) -c 'kpas' -C 'kpas' -s "KPass_AlfredWorkflow" -w "/Users/.........../Library/Keychains/login.keychain-db" | keepassxc-cli ls -R -q -f "/Users/......../Documents/Work/CFN/coffre-systeme.kdbx"
```

You have to change the ........ with your user / correct path.

Regarding the keychainItem, you need it to be able to unlock the database.

KPass works as follow, when you configure the database you are asked to enter the password to unlock it. This password is stored in the keychain and when using KPass this password is used to list and get the passwords using the commands shown.

Thanks

**Comment by pdomineaux** [comment]
Hello, 
Thanks for that quick reply.
The output of the first command is (I think) an "Hashed" password.
The output of the second one (combined with "keepass-cli" is showing nothing.

I've tried to specified a bad password in my keychain in order to see if in that case I can see an error message, but it failed too. Nothing in the output.
This command give me the expected result : `keepassxc-cli show /Users/........../Documents/Work/CFN/coffre-systeme.kdbx my_entry`
But the same combined with KPass : 
`security find-generic-password -a $(id -un) -c 'kpas' -C 'kpas' -s "KPass_AlfredWorkflow" -w "/Users/.........../Library/Keychains/login.keychain-db" | keepassxc-cli show /Users/........../Documents/Work/CFN/coffre-systeme.kdbx omero_prod `

Return : ```Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt.```

Thanks for your help.

**Comment by Angoll** [comment]
That's should be the issue, the password shown by the first command should not be hashed in any way. I recommend you to check the keychainItem in environment variables and run again the KPass setup to setup the password correctly, or open keychain and update the value with the password for the database.

Thanks

**Comment by pdomineaux** [comment]
Ok I've found it.
It seems that the password is hashed if any symbol is not supported by the keychain.
In my case issue was not with `'` or `!` but with that french symbol `è`.
This is a shared password on a shared database, so I have to ask my team if we can change it.

So the issue is not with your code which work like a charm but with the keychain management.
Thanks for your help.
