### ISSUE TITLE
Failed to load key file but it exactly exists.

### ISSUE THREAD

**Issue by RealForce1024** [Angoll/KPass#12]
Failed to load key file but it exactly exists.

**Comment by RealForce1024** [comment]
alfred 4.3.2 
keepassxc 2.6.2
KPass alfredworkflow 2.1

**Comment by RealForce1024** [comment]
> Failed to load key file but it exactly exists.

{"items": [{"title":"Error listing database, please check config: Error: Enter password to unlock ~/Users/xxx/yy.kdbx: Failed to load key file \"/Users/xxx/ianyue.key\": No such file or directory"}]}.   the key file location is exactly exists

**Comment by Angoll** [comment]
Hello @IT-ACG 

can you try to use absolute paths?

From the error it seems that is trying to open a file `~/Users/xxx/yy.kdbx` and it should be `/Users/xxx/yy.kdbx`

Let me know if that fix the issue
Thanks

**Comment by RealForce1024** [comment]
Yea I known it, I just for hidden my path. But No worked yet.   
`{"items": [{"title":"Error listing database, please check config: Error: Enter password to unlock /Users/fqc/D..../password/x.kdbx: Failed to load key file \"/Users/fqc/D...../password/x.key\": No such file or directory"}]}  `

**Comment by atttx123** [comment]
> Yea I known it, I just for hidden my path. But No worked yet.
> `{"items": [{"title":"Error listing database, please check config: Error: Enter password to unlock /Users/fqc/D..../password/x.kdbx: Failed to load key file \"/Users/fqc/D...../password/x.key\": No such file or directory"}]} `

same issue

**Comment by Angoll** [comment]
@IT-ACG  I upload a new version with @atttx123  changes, that solved the problem for him, please check the new version and let me know if the issue can be closed.

Thanks
