### ISSUE TITLE
Unexpectedly slow

### ISSUE THREAD

**Issue by NeighNeighNeigh** [Angoll/KPass#13]
There is a significant delay between evoking the command and returning any results. It sits there with "KpassLoader - Please loading database…" for about 10 seconds before showing anything, should I expect it to be faster? My keepass database is not huge (453 entries)

**Comment by nmajin** [comment]
It’s due to how the json list is built for the menu in Alfred. I wish it was faster myself but the code is building each json item block one by one.

**Comment by NeighNeighNeigh** [comment]
Ah okay, thanks for clarifying the issue

**Comment by Angoll** [comment]
Please check the new README.md and this issue #17  to fully understand that the issue is more related to a configuration in keepassxc.
