### ISSUE TITLE
Add Fingerprint (or password) before Database gets queried

### ISSUE THREAD

**Issue by kalaschnik** [Angoll/KPass#16]
I really enjoy using the workflow; yet, as it is bypassing the master password, it would be good if there is an option to provide a fingerprint (or user password) before the database entries are displayed.

**Comment by nmajin** [comment]
It’s not bypassing the password, it’s configured in Keychain and then passed to keepassxc CLI. This would be a horrible idea and would defeat the purpose of getting the password quick.

**Comment by kalaschnik** [comment]
I get the point of convenience—which is why I was looking for a workflow and eventually installed this one. Nonetheless, if I would have my laptop unlocked and leave the room an attacker has full access to my entire password database if they are aware of me using Kpass. I know, I know, this is super unlikely, but if there would be a fingerprint gatekeeper before displaying the hits users could opt-in for another layer of security.

**Comment by Angoll** [comment]
Hello @Kalaschnik,

As nmajin mentioned we store the master password in the keychain to use it with keepassxc-cli.
I think your scenario doesn't apply, as a user that gain access to your computer also can find open sessions 😅 . For me your scenario would be solved (or minimised) with the use of auto lock and require password immediately.

We currently are quite limited in what keepassxc-cli offers as is our only way to access the keepassxc without need to fork the keepassXC code.

I tried to configure a different keychain with out granting always permissions for the workflow but is constantly asking and not woking correctly with Alfred as the menu disappears when the popup to request the password appear.
