### ISSUE TITLE
KPass enhancement

### ISSUE THREAD

**Issue by atttx123** [Angoll/KPass#17]
Hi @Angoll

I added some new features to KPass：

- feat: `kpass` command support fuzzy search
- feat: reduce the `kpass` command delay to less than 5 seconds #13 
- fix: command not found: keepassxc-cli
- fix: #12 

Unfortunately, I do not know how to change the Alfred Wrokflow settings, so I export a `alfredworkflow` file below
[KPass.zip](https://github.com/Angoll/KPass/files/6891162/KPass.zip)

For the script diff, I will create a pull request soon.

Looking forward to receiving your feedback.

**Comment by atttx123** [comment]
Unfortunately, the final delay of the `kpass` command depends on the `keepassxc-cli` command.

 In my test, the `keepassxc-cli` command is very slow.

 It should be determined that it is the problem of `KeepPassXC` itself, not the workflow script.

![image](https://user-images.githubusercontent.com/1284339/127285306-2fc186f5-805e-43e9-b92a-ad947d67fcc3.png)

**Comment by atttx123** [comment]
As mentioned https://github.com/keepassxreboot/keepassxc/issues/6778, change database type to `KDF 4` can effectively increase the speed
![image](https://user-images.githubusercontent.com/1284339/127493751-27a890ab-ac8f-4bd0-90f2-ca13e06d9a3b.png)


now `kpass` command can open in 1 second

https://user-images.githubusercontent.com/1284339/127487148-80142eaf-5b9e-4ec2-b070-32d62bdab9be.mp4

**Comment by Angoll** [comment]
Thanks @atttx123  for your time!

I merged the changes and released a new version, adding comments to this issue in the readme.

**Comment by Ashok-Varma** [comment]
New version has bugs #19
