### ISSUE TITLE
Fuzzy search possible?

### ISSUE THREAD

**Issue by nmajin** [Angoll/KPass#24]
Is there any way we can get a fuzzy search on the entries? I am having to put the exact characters, including slashes at some points and quotes or brackets around named entries in order to match properly.

i.e.
![image](https://user-images.githubusercontent.com/253669/152092615-b59b4827-8ec6-4a04-bf47-154926f51c8d.png)

But If I add the slashes then I can get to the entry:
![image](https://user-images.githubusercontent.com/253669/152092697-2347116a-ad41-4236-b0dd-c5ac4aabcdb8.png)

**Comment by zkytech** [comment]
I have made a pr #23  to boost search speed which also supports fuzzy search

**Comment by nmajin** [comment]
Awesome. Thanks!

**Comment by Angoll** [comment]
Hello, insted of trying to implement a fuzzy search I would suggest to try different Alfred match modes:

![image](https://user-images.githubusercontent.com/5797311/159095257-0e83797b-6c09-417d-9277-5b10fe8f86e9.png)

**Comment by nmajin** [comment]
> 

I tried the match mode in Alfred and didn't quite work out...whatever changes are implemented in the latest release is working out fine. Thanks, will also close out this issue.
