### ISSUE TITLE
Getting ERROR: KPass[Script Filter] Code 127: libpng warning: iCCP: known incorrect sRGB profile /Users/.../Library/Caches/... line 35: jq: command not found

### ISSUE THREAD

**Issue by Cartache** [Angoll/KPass#25]
Hi,

Thank you for your work and this beautiful piece of coding.
I am facing multiple issues and try to proceed step by step.
The first one is this error raised when running the script.

I checked in the other issues and found that this error is raised in case of missing jq.

I reinstall it and can confirm it is working.
Terminal -> jq -> 
`jq - commandline JSON processor [version 1.6]

Usage:	jq [options] <jq filter> [file...]
	jq [options] --args <jq filter> [strings...]
	jq [options] --jsonargs <jq filter> [JSON_TEXTS...]

jq is a tool for processing JSON inputs, applying the given filter to
its JSON text inputs and producing the filter's results as JSON on
standard output.

The simplest filter is ., which copies jq's input to its output
unmodified (except for formatting, but note that IEEE754 is used
for number representation internally, with all that that implies).

For more advanced filters see the jq(1) manpage ("man jq")
and/or https://stedolan.github.io/jq

Example:

	$ echo '{"foo": 0}' | jq .
	{
		"foo": 0
	}

For a listing of options, use jq --help.`

May I ask you some hints to find my problem?

Thanks. 

Denis

**Comment by zkytech** [comment]
1. Run this command:
```bash
which jq
```
2. replace all `jq` in the script with the result of step 1

**Comment by Cartache** [comment]
Hi, thank you for your rapid answer. I made the change. I found only 1 occurence is this normal? Anyway, after the change jq -> /usr/bin/jq 

Now I got this weird error about none existent file : `[11:11:36.560] ERROR: KPass[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.734398F6-0A8A-4DC9-BE12-340C77C031F1%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Code 127: libpng warning: iCCP: known incorrect sRGB profile /Users/dbi/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/435668D0-236B-4D8A-B4E7-79178126D632: line 35: /usr/bin/jq: No such file or directory`

If I type /usr/bin/jq in terminal and I got a positive help message I already copied above.

**Comment by Angoll** [comment]
Hi,
The issue is that the variable PATH in the script is not the same as the PATH in the terminal, and therefore its not finding the `jq` binary.

If you replace the line 
```export PATH='/usr/.....'```

with the following it should work:
```export PATH='/usr/local/bin/:/usr/bin:/Applications/KeePassXC.app/Contents/MacOS/:/opt/homebrew/bin:${PATH}'```

If still not working in the Terminal do `echo $PATH` and use that as the value of the export PATH='...'

**Comment by Angoll** [comment]
Give release 2.4 a try, I fixed some of this issues
