### ISSUE TITLE
Problem with getting the password in the clipboard

### ISSUE THREAD

**Issue by Astrakan27** [Angoll/KPass#26]
I have installed and configured the workflow. The list of entries is appropriately showing up but I'm getting an erro when the script try to get and password and copy it to the clipboard

Error message is the following:

Passing output 'Enter password to unlock /Users/xxxx/xxxx/database.kdbx: Error while reading the database: Invalid credentials were provided, please try again. If this reoccurs, then your database file may be corrupt. (HMAC mismatch)

My database works perfectly outside the workflow

It seems to me that the issue is related to there handling of the Key File by the script

Any suggestion please?

Thanks
Astrakan

**Comment by Angoll** [comment]
Hello, please try the version 2.4 I fixe some issues with using the key

**Comment by Astrakan27** [comment]
Thank you very much Angoll, not it works
