### ISSUE TITLE
keepassxc-cli locate no longer exists?

### ISSUE THREAD

**Issue by nmajin** [Angoll/KPass#27]
I recently upgraded to KeePassXC 2.7.0 and I was getting an error getting the db_keys and dug into the issue that it appears the `locate` command is no longer available. I was trying to substitute `ls` but I am getting just a single stream of entries returned. I assume the locate command provided a bit more info to parse the keys out.

**Comment by nmajin** [comment]
Any update or is the issue just me?

**Comment by witeshadow** [comment]
Per KeePassXC github.  
https://github.com/keepassxreboot/keepassxc/pull/6805

**Comment by nmajin** [comment]
> Per KeePassXC github. [keepassxreboot/keepassxc#6805](https://github.com/keepassxreboot/keepassxc/pull/6805)

Thanks for the heads up, looks like search may work, but seeing some funky results with some of the code where it seems like the search term, "/" is not picking up all the entries...

```
a_test_1
a_test_2
a_test_3
```

```
keys=($(security find-generic-password -a $(id -un) -c 'kpas' -C 'kpas' -s KPass_AlfredWorkflow -w /Users/<user>/Library/Keychains/login.keychain-db | keepassxc-cli search "<path to db>/passwords.kdbx" / -q))
```

```
echo ${keys[@]} | sed 's/ \//\n\//g' | awk -v iconPath="${PWD}/icon.png" '{printf "{\"uid\":\"%s\", \"title\":\"%s\", \"subtitle\":\"%s\", \"arg\":\"%s\", \"autocomplete\": \"%s\", \"icon\":{\"type\":\"png\", \"path\": \"%s\"}}", $0, substr($0,2, length($0)), $0, $0, $0, iconPath}' | jq -c -s '{"items": .}' | jq
```

From the output I don't see all these entries at all...if i change the search term to `a_test` then I get all 3 hits...I tried `.` for the search term as well and still no luck.

Edit: I just tried using "*" for the search term and that appears to work. I'll mess around a little more and if this solves the issue I will mark this closed.

**Comment by Angoll** [comment]
@nmajin  I created a new release v2.5, give it a try!
