### ISSUE TITLE
Error Listing Database

### ISSUE THREAD

**Issue by ITRecords38** [Angoll/KPass#5]
Hi,

after having informed my base and my key, he cannot list my keychain (See Screenshot)

Thanks for help
<img width="515" alt="ITRecords 1" src="https://user-images.githubusercontent.com/19632490/92321441-424f3000-f02a-11ea-8d20-a13e4dbb4176.png">

**Comment by pdomineaux** [comment]
Hello, same issue here.
But it works with another database.

**Comment by Angoll** [comment]
Hello @GrimlocK38 and @pdomineaux, thanks for the feedback.

Have you tried to configure it again?

I recommend upgrading to V2 (now released) that improves error information, the error gets copied to the clipboard for easy debugging.

Looking forward for your replies.

**Comment by ITRecords38** [comment]
Hi,

Thanks for update. always the same problem

**Comment by Angoll** [comment]
Can you check that the environment variables are set correctly?

Show Alfred preferences > Workflows > KPass > [x]   

This should show you the Workflow environment variables:

 - **database**:  Should have the full path to the database file, as example: _/Users/myuser/keepassDB.kdbx_
 - **keychain**: Should point to the keychain file, as example: _/Users/myuser/Library/Keychains/login.keychain-db_
 - **keePassKeyFile**: can be empty, full path to the key file if required to open the database
 - **keychainItem**: by default KPass_AlfredWorkflow

The value of KPass_AlfredWorkflow is the keychain item created in the selected keychain that securely stores the password for your database. If you open the keychain app you should be able to check that the password for your database is correctly stored.

Hope this help, please let me know what was the issue.

**Comment by ITRecords38** [comment]
Ok for me no ?

<img width="1642" alt="ITRecords 1" src="https://user-images.githubusercontent.com/19632490/97081267-7c3bbc00-1601-11eb-8c99-40c55b58572f.png">

**Comment by Angoll** [comment]
It looks good to me.

Can you check the error message if you type kpass in alfred?

Whit V2 the error messages are more descriptive and press enter to copy it to the clipboard so you can paste it and check the full message.

**Comment by ITRecords38** [comment]
/Users/itrecords/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/07AC2BF8-EB65-4F10-BC30-8203963FDF2A: line 17: keepassxc-cli: command not found

**Comment by Angoll** [comment]
so the issue is that for some reason you don't have the keepassxc-cli binary in your PATH variable.

Can you try to open a terminal and run this command:

```bash
ln -s /Applications/KeePassXC.app/Contents/MacOS/keepassxc-cli /usr/local/bin/keepassxc-cli
```
This command will create a symlink to the keepassxc-cli and will add it to the PATH variable.

**Comment by ITRecords38** [comment]
Perfect. It Work 💪🏻 
Thank You 😀
