### ISSUE TITLE
Adding key file if needed

### ISSUE THREAD

**Issue by thibpoullain** [Angoll/KPass#6]
Hi ! Thx for your work !

I use a keyfile with my database and it seems like it not supported by the setup script for now.

I'd like to the add functionnality and propose a merge request, but don't know the alfred API for applescript. Where could I find the doc ? 

Thx :)

**Comment by Angoll** [comment]
Hello @thibpoullain, thanks for the feedback.

I just had time to dedicate to this project (new v2), I added a new part where it asks for the key file and integrate it.

Regarding some of the documentation I used:
- https://developer.apple.com/library/archive/documentation/LanguagesUtilities/Conceptual/MacAutomationScriptingGuide/index.html
- https://computers.tutsplus.com/tutorials/a-beginners-guide-to-javascript-application-scripting-jxa--cms-27171
