### ISSUE TITLE
Search current opened DB

### ISSUE THREAD

**Issue by daletman** [Angoll/KPass#8]
Hi Angoll,

first thanks for providing your work for free.

Is there a way to just search the currently opened DB in KeePassXC instead of selecting a specific one?

**Comment by Angoll** [comment]
Helllo,
Thanks for the feedback, I'm not currently aware any way to accomplish that.
From my point of view the GUI talks to the KeePassXC Core and opens a database, but to be able to interface with the core I'm using the keepassxc-cli.
