### ISSUE TITLE
"Could not find entry with path" when copying password

### ISSUE THREAD

**Issue by mirkonz** [Angoll/KPass#9]
Hi there I'm getting following error when copying the password. I'm guessing it somehow doesn't like the space in the folder and/or file name?
Search works fine btw.
```
[07:14:17.767] KPass[Script Filter] Passing output 'my folder/my entry' to Run Script
[07:14:18.829] STDERR: KPass[Run Script] Could not find entry with path my.
```

**Comment by Angoll** [comment]
Hello @mayko780, are you using v2 of KPass?
version 1 has an issue with the spaces in the entries that should be fixed in v2

**Comment by mirkonz** [comment]
Yep, I've just upgraded to v2.

**Comment by Angoll** [comment]
I find the issue I updated a new 2.1 please update or apply the fix.

Thank you for reporting it

Fix changes:
https://github.com/Angoll/KPass/commit/900f1a221d538d363dc032a8f74b8894e66415ec

**Comment by mirkonz** [comment]
Amazing. Thanks for the instant fix! 👍
